# Change these first
owner: Wiselink # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
- name: API Regis - Login(DEV)
  url: https://www.gianlucatupapito.xyz/api/registration/users/ZeLytRmZ78RSgwXCEsktT1Zg63k1
  method: GET
  maxResponseTime: 5000
- name: API Regis - User Data(DEV)
  url: https://www.gianlucatupapito.xyz/api/registration/users/ZeLytRmZ78RSgwXCEsktT1Zg63k1/data
  method: GET
  maxResponseTime: 5000
- name: API Regis - Identities(DEV)
  url: https://www.gianlucatupapito.xyz/api/registration/users/ZeLytRmZ78RSgwXCEsktT1Zg63k1/identities
  method: GET
  maxResponseTime: 5000
- name: API Regis - Search Catgs(DEV)
  url: https://www.gianlucatupapito.xyz/api/registration/data/search-catg
  method: GET
  maxResponseTime: 5000
- name: API Regis - Get Options(DEV)
  url: https://www.gianlucatupapito.xyz/api/registration/data/options
  method: GET
  maxResponseTime: 5000
- name: API Regis - Search User by name/lastname(DEV)
  url: https://www.gianlucatupapito.xyz/api/registration/users/search
  method: GET
  maxResponseTime: 5000
- name: API Comps - Comps - Get Company(DEV)
  url: https://www.gianlucatupapito.xyz/api/companies-data/companies/dbc2924a-7600-4113-b39f-8d15b08517a9
  method: GET
  maxResponseTime: 5000
- name: API Comps -Comps - Get Comps by owner(DEV)
  url: https://www.gianlucatupapito.xyz/api/companies-data/companies/owner/Locpg72yDNRN4Quvx20BWs8NLSG2
  method: GET
  maxResponseTime: 5000
- name: API Coms - Comps - Get comp identities(DEV)
  url: https://www.gianlucatupapito.xyz/api/companies-data/companies/owner/Locpg72yDNRN4Quvx20BWs8NLSG2/identities
  method: GET
  maxResponseTime: 5000
- name: API Comps - Comps - Get comp status(DEV)
  url: https://www.gianlucatupapito.xyz/api/companies-data/companies/dbc2924a-7600-4113-b39f-8d15b08517a9/status
  method: GET
  maxResponseTime: 5000
- name: API Comps - Out C - Get Comp(DEV)
  url: https://www.gianlucatupapito.xyz/api/companies-data/out-companies/81aaadc9-cb56-4a2a-981a-e121d3bc18ba
  method: GET
  maxResponseTime: 5000
- name: API Comps - Out C - Get Comp by owner(DEV)
  url: https://www.gianlucatupapito.xyz/api/companies-data/out-companies/owner/Locpg72yDNRN4Quvx20BWs8NLSG2
  method: GET
  maxResponseTime: 5000
- name: API Comps - Out C - Get Comp Idents(DEV)
  url: https://www.gianlucatupapito.xyz/api/companies-data/out-companies/owner/Locpg72yDNRN4Quvx20BWs8NLSG2/identities
  method: GET
  maxResponseTime: 5000
- name: API Comps - BackOff - Get on hold(DEV)
  url: https://www.gianlucatupapito.xyz/api/companies-data/back-office/companies?state=on_hold
  method: GET
  maxResponseTime: 5000
- name: API Comps - GrlData - Options(DEV)
  url: https://www.gianlucatupapito.xyz/api/companies-data/data/options
  method: GET
  maxResponseTime: 5000
  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
