# Change these first
owner: Wiselink # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
# - name: FRONT(DEV)
#   url: https://www.gianlucatupapito.xyz
#   method: GET
#   maxResponseTime: 5000
# - name: API Regis - Login(DEV)
#   url: https://www.gianlucatupapito.xyz/api/registration/users/tQvx3WPi4ae5yhA0ZUtqcg6Hzwu1
#   method: GET
#   maxResponseTime: 5000
# - name: API Regis - User Data(DEV)
#   url: https://www.gianlucatupapito.xyz/api/registration/users/tQvx3WPi4ae5yhA0ZUtqcg6Hzwu1/data
#   method: GET
#   maxResponseTime: 5000
# - name: API Regis - Identities(DEV)
#   url: https://www.gianlucatupapito.xyz/api/registration/users/tQvx3WPi4ae5yhA0ZUtqcg6Hzwu1/identities
#   method: GET
#   maxResponseTime: 5000
# - name: API Regis - Search Catgs(DEV)
#   url: https://www.gianlucatupapito.xyz/api/registration/data/search-catg
#   method: GET
#   maxResponseTime: 5000
# - name: API Regis - Get Options(DEV)
#   url: https://www.gianlucatupapito.xyz/api/registration/data/options
#   method: GET
#   maxResponseTime: 5000
# - name: API Regis - Search User by name/lastname(DEV)
#   url: https://www.gianlucatupapito.xyz/api/registration/users/search
#   method: GET
#   maxResponseTime: 5000
# - name: API Comps - Comps - Get Company(DEV)
#   url: https://www.gianlucatupapito.xyz/api/companies-data/companies/a424beb7-cb70-439a-b9e5-1d8520ef8ae4
#   method: GET
#   maxResponseTime: 5000
# - name: API Comps -Comps - Get Comps by owner(DEV)
#   url: https://www.gianlucatupapito.xyz/api/companies-data/companies/owner/tQvx3WPi4ae5yhA0ZUtqcg6Hzwu1
#   method: GET
#   maxResponseTime: 5000
# - name: API Coms - Comps - Get comp identities(DEV)
#   url: https://www.gianlucatupapito.xyz/api/companies-data/companies/owner/tQvx3WPi4ae5yhA0ZUtqcg6Hzwu1/identities
#   method: GET
#   maxResponseTime: 5000
# - name: API Comps - Comps - Get comp status(DEV)
#   url: https://www.gianlucatupapito.xyz/api/companies-data/companies/a424beb7-cb70-439a-b9e5-1d8520ef8ae4/status
#   method: GET
#   maxResponseTime: 5000
# - name: API Comps - Out C - Get Comp(DEV)
#   url: https://www.gianlucatupapito.xyz/api/companies-data/out-companies/a5e613d9-7f27-42a1-8cd2-08507fdbafaf
#   method: GET
#   maxResponseTime: 5000
# - name: API Comps - Out C - Get Comp by owner(DEV)
#   url: https://www.gianlucatupapito.xyz/api/companies-data/out-companies/owner/tQvx3WPi4ae5yhA0ZUtqcg6Hzwu1
#   method: GET
#   maxResponseTime: 5000
# - name: API Comps - Out C - Get Comp Idents(DEV)
#   url: https://www.gianlucatupapito.xyz/api/companies-data/out-companies/owner/tQvx3WPi4ae5yhA0ZUtqcg6Hzwu1/identities
#   method: GET
#   maxResponseTime: 5000
# - name: API Comps - BackOff - Get on hold(DEV)
#   url: https://www.gianlucatupapito.xyz/api/companies-data/back-office/companies?state=on_hold
#   method: GET
#   maxResponseTime: 5000
# - name: API Comps - GrlData - Options(DEV)
#   url: https://www.gianlucatupapito.xyz/api/companies-data/data/options
#   method: GET
#   maxResponseTime: 5000
# - name: API Emps - Get company emps(DEV)
#   url: https://www.gianlucatupapito.xyz/api/employment/employees/company/a424beb7-cb70-439a-b9e5-1d8520ef8ae4
#   method: GET
#   maxResponseTime: 5000
# - name: API Emps - Get Empl user/comp tokens(DEV)
#   url: https://www.gianlucatupapito.xyz/api/employment/employees/user/tQvx3WPi4ae5yhA0ZUtqcg6Hzwu1/company/a424beb7-cb70-439a-b9e5-1d8520ef8ae4
#   method: GET
#   maxResponseTime: 5000
# - name: API Emps - Get Empl user token(DEV)
#   url: https://www.gianlucatupapito.xyz/api/employment/employees/user/tQvx3WPi4ae5yhA0ZUtqcg6Hzwu1
#   method: GET
#   maxResponseTime: 5000
# - name: API Emps - Get Empl job ofers(DEV)
#   url: https://www.gianlucatupapito.xyz/api/employment/employees/user/tQvx3WPi4ae5yhA0ZUtqcg6Hzwu1/offer
#   method: GET
#   maxResponseTime: 5000
# - name: API Emps - Get Empl by token
#   url: https://www.gianlucatupapito.xyz/api/employment/employees/employee/782bb3c5-46bc-4431-ba9a-7d3a23c92d1f/company/a424beb7-cb70-439a-b9e5-1d8520ef8ae4
#   method: GET
#   maxResponseTime: 5000
# - name: API DigCatlg - Get Prod(DEV)
#   url: https://www.gianlucatupapito.xyz/api/digital-catalog/product/product-2ccd5004-c767-4430-9528-c1cc1e11ae51/company/a22f2eb4-fdc8-4416-97dc-4ee2de942e6a
#   method: GET
#   maxResponseTime: 5000
# - name: API DigCatlg - Get Serv(DEV)
#   url: https://www.gianlucatupapito.xyz/api/digital-catalog/service/service-07a4674a-61ae-4d6f-ab33-b796e18a3275/company/a424beb7-cb70-439a-b9e5-1d8520ef8ae4
#   method: GET
#   maxResponseTime: 5000
# - name: API DigCatlg - Get Line(DEV)
#   url: https://www.gianlucatupapito.xyz/api/digital-catalog/product-line/line-d71491b6-3b1a-46ba-9486-35432319b504/company/dbc2924a-7600-4113-b39f-8d15b08517a9
#   method: GET
#   maxResponseTime: 5000
# - name: API DigCatlg - Get Line Items(DEV)
#   url: https://www.gianlucatupapito.xyz/api/digital-catalog/product-line/company/dbc2924a-7600-4113-b39f-8d15b08517a9/prod-serv
#   method: GET
#   maxResponseTime: 5000
# - name: API DigCatlg - Get category tree
#   url: https://gianlucatupapito.xyz/api/digital-catalog/category/
#   method: GET
#   maxResponseTime: 5000

  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
